[package]
name = "hexcede/chlorine"
description = "A luau sandbox designed to work with Matter."
version = "0.1.0"
license = "MIT"
authors = ["Hexcede"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]


[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"